---
version: "3"

services:
  app:
    image: roquefort/prometheus-jira-cloud-exporter:latest
    build: .
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ./config.py:/app/config.py:ro
