---
version: "3"

services:
  app:
    image: roquefort/prometheus-jira-cloud-exporter:latest
    build: .
    env_file: ./.env
    restart: always
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./config.py:/app/config.py:ro
