---
version: "3"

services:
  app:
    image: roquefort/prometheus-jira-cloud-exporter:latest
    build: .
    env_file: ./.env
    restart: unless-stopped
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./.env:/app/.env:ro
